// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ToastsExampleApp",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "ToastsExampleApp",
            targets: ["AppModule"],
            bundleIdentifier: "sample.ToastsExampleApp",
            teamIdentifier: "7CS3Y36YYN",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bird),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(name: "toast-alerts", path: "..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Toasts", package: "toast-alerts")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
